### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by RichardCorbett** [rujinwang/SCOPE_tutorial#3]
Hi folks,
I'm hoping to try out your tool.     Is there a version of R that I should target first?

thanks
Richard

**Comment by rujinwang** [comment]
Hi, 
You need to install R versions >= 3.5.0. Thanks. 

Rujin

**Comment by RichardCorbett** [comment]
Thanks.

I tried the commands as written [here](https://github.com/rujinwang/SCOPE) and got the following error.   Should I also be installing some BiocManager packages?

thanks
RIchard


```
install.packages('devtools') # works without error

devtools::install_github("rujinwang/SCOPE/package")
Downloading GitHub repo rujinwang/SCOPE@master
Skipping 6 packages not available: GenomicRanges, IRanges, Rsamtools, BSgenome.Hsapiens.UCSC.hg19, GenomeInfoDb, CODEX2
Installing 11 packages: Rsamtools, BSgenome.Hsapiens.UCSC.hg19, CODEX2, DescTools, gplots, manipulate, mvtnorm, expm, gtools, gdata, caTools
Installing packages into ‘/home/rcorbett/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Error: Failed to install 'SCOPE' from GitHub:
  (converted from warning) packages ‘Rsamtools’, ‘BSgenome.Hsapiens.UCSC.hg19’, ‘CODEX2’ are not available (for R version 3.6.0)

```

**Comment by rujinwang** [comment]
Yes, you should install Rsamtools, BSgenome.Hsapiens.UCSC.hg19, CODEX2 packages beforehand. Thanks. 

Rujin

**Comment by RichardCorbett** [comment]
Thanks.  I think I have it running now.

My data are single cell whole genome data.   Do I still need to provide an exome bed file?  If so, where do I get a copy of 'scWGA500kb.bed'?

thanks
Richard

**Comment by yuchaojiang** [comment]
Hi Richard,

No you don’t need the exome bed file. However, you do need a bed file for the bins. We started with a 500Kb bin size (Rujin, please make this file available).

Note that our paper is currently under revision and the package is still a beta version. There will be constant updates and we will release a formal version together with the published paper.

Thanks!

Yuchao

On Aug 26, 2019, at 7:14 PM, Richard Corbett <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks. I think I have it running now.

My data are single cell whole genome data. Do I still need to provide an exome bed file? If so, where do I get a copy of 'scWGA500kb.bed'?

thanks
Richard

**Comment by rujinwang** [comment]
Hi Richard, 
I just upload the scWGA500kbsort.bed file. You can use it as the bed file for whole genome bins. Thanks. 

Rujin

**Comment by RichardCorbett** [comment]
Thanks Rujin,

I got a little farther, but now it seems I can't read my BAM files.  When I check the path on the command line the file is available and readable with samtools/sambamba.
`
Error in value[[3L]](cond) : failed to open BamFile: SAM/BAM header missing or empty file: '/projects/rcorbettprj2/SCOPE/B44746_ACTGAT-ACCCAG_GSC-CSC_Nuclei_1.bam_RG_added.bam'
`

```
ls -la /projects/rcorbettprj2/SCOPE/B44746_ACTGAT-ACCCAG_GSC-CSC_Nuclei_1.bam_RG_added.bam
-rw-r--r-- 1 rcorbett users 84753362 Aug 26 13:38 /projects/rcorbettprj2/SCOPE/B44746_ACTGAT-ACCCAG_GSC-CSC_Nuclei_1.bam_RG_added.bam
```

thanks,
Richard

**Comment by yuchaojiang** [comment]
You miss the header information for your bam file. This is from upstream bioinformatic processing.

**Comment by RichardCorbett** [comment]
Thanks.  It turns out we have some arabidopsis single cell data mixed in here which seems to be the problem.

**Comment by RichardCorbett** [comment]
It looks like I'm having some difficulty with the later steps.  I've removed the 'chr' strings from the chromosome names in the scWGA500kbsort,GRCh37GenomicSuperDup, and  hg19gaps reference files to match the reference in my BAM file, so that might be causing the problem, though I don't see any errors until I get to the QC commands:

```
# Get segmental duplication regions
seg.dup = read.table(system.file("extdata", "GRCh37GenomicSuperDup_noChr.tab", package = "SCOPE"), head = T)
seg.dup = seg.dup[!is.na(match(seg.dup[,1], c(1:22, 'X', 'Y'))),]
seg.dup = GRanges(seqnames = seg.dup[,1], ranges = IRanges(start=seg.dup[,2], end = seg.dup[,3]))
# Get hg19 gaps
gaps = read.table(system.file("extdata", "hg19gaps_noChr.tab", package = "SCOPE"), head = T)
gaps = gaps[!is.na(match(gaps[,2], c(1:22, 'X', 'Y'))),]
gaps = GRanges(seqnames = gaps[,2], ranges = IRanges(start = gaps[,3], end = gaps[,4]))
# Generate mask region
mask.ref = sort(c(seg.dup, gaps))

# Getting raw read depth
coverageObj <- getcoverage.scDNA(bambedObj, mapqthres = 40, mask.ref, seq='paired-end')
Y_raw <- coverageObj$Y

...
The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)Getting coverage for sample 5: B44751_GCCTTA-ACCCAG_DeadCell_Nuclei_1...
The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)Getting coverage for sample 6: B44752_TCCCGA-ACCCAG_DeadCell_Nuclei_1...
...

> qcObj = qc_scope(Y_raw = Y_raw, sampname_raw = sampname_raw, ref_raw = ref_raw, QCmetric_raw = QCmetric_raw)
Removed 1325 samples due to failed library preparation.
Removed 4 samples due to low proportion of mapped reads.
Excluded 200 bins due to extreme GC content.
Excluded 321 bins due to low mappability.
Error in apply(apply(Y.nonzero, 2, function(x) { : 
  dim(X) must have a positive length

```

**Comment by rujinwang** [comment]
Hi Richard, 
Is it possible for your to share one or two questionable samples with me? I cannot tell what's wrong until I can play with the data. It seems like your chromosome names are not found in reference genome. 

Rujin

**Comment by RichardCorbett** [comment]
Sure.  I have posted a couple of human cell line BAM files at this location:
http://www.bcgsc.ca/downloads/rcorbett/SCOPE/
thanks
RIchard

**Comment by rujinwang** [comment]
Hi Richard, 
I've looked into yourBAM files. I didn't get any errors. How do you remove the "chr" strings from the reference genome? Make sure you changed the sequence levels. You can directly use seqlevels(). 
Actually we just updated the package. Can you try to re-install SCOPE and see how it works? If you still get errors, I can share my scripts with you. Just let me know. Thanks. 

Rujin
