### ISSUE TITLE
errors when running demo code of tutorial

### ISSUE THREAD

**Issue by xikanfeng2** [rujinwang/SCOPE_tutorial#6]
I am trying the tutorial step by step and found two errors.
1. The line of  'bambedObj <- getbambed_scope(bamdir = bamdir, bedFile = bedFile, sampname = sampname_raw)' in 2.1. The error information is
`Error in getbambed_scope(bamdir = bamdir, bedFile = bedFile, sampname = sampname_raw) : 
  unused argument (bedFile = bedFile)`. when I remove this bedFile argument, this line works.
2. The line of 'coverageObj <- getcoverage.scDNA(bambedObj, mapqthres = 40, mask.ref, seq='paired-end')' in 2.3. The error information is 
`Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments`. I think this error may be caused by the 'mask.ref' object.

Could you help me to work out these two errors cause i want to run the whole demo code of your tutorial?

**Comment by rujinwang** [comment]
Hi, 
This repository is not maintained. We update the package to conform to Bioconductor guideline. 
Please go to https://github.com/rujinwang/SCOPE and follow the vignette. Sorry about the confusion. Let me know if you have any problems. 

Thanks. 

Rujin

**Comment by xikanfeng2** [comment]
> Hi,
> This repository is not maintained. We update the package to conform to Bioconductor guideline.
> Please go to https://github.com/rujinwang/SCOPE and follow the vignette. Sorry about the confusion. Let me know if you have any problems.
> 
> Thanks.
> 
> Rujin

Thanks.
